### ISSUE TITLE
可以提供一下项目的sql吗

### ISSUE THREAD

**Issue by 820252044** [huiboxes/kindergarten_sys#1]
可以提供一下项目的sql吗

**Comment by huiboxes** [comment]
> 可以提供一下项目的sql吗

不好意思，这个项目是当初弄着玩的。当初的机械硬盘坏了，sql找不到了。你可以根据代码实体类来创数据库。

**Comment by huiboxes** [comment]
实体类在各个包下，比如家长表对应的实体类在：src/main/java/com/ruoyi/project/kinder_parent/domain/ 下面。
